// =============================================================================
// ROOT LAYOUT - THE FOUNDATION OF YOUR NEXT.JS APP
// =============================================================================
// This is the ROOT LAYOUT file (app/layout.tsx) - the most important layout file.
// It wraps ALL pages in your application and is required in every Next.js app.
//
// Key concepts:
//   - layout.tsx files define UI that is SHARED across multiple pages
//   - The root layout MUST contain <html> and <body> tags
//   - Layouts preserve state and don't re-render when navigating between pages
//   - This file is a Server Component by default
//
// File structure:
//   app/
//   ├── layout.tsx      <- This file (root layout, wraps everything)
//   ├── page.tsx        <- Home page (/)
//   ├── about/
//   │   ├── layout.tsx  <- Nested layout (wraps only /about/* pages)
//   │   └── page.tsx    <- About page (/about)
//   └── ...
//
// When a user visits /about:
//   1. Root layout renders first (this file)
//   2. About layout renders inside root layout (if exists)
//   3. About page renders inside about layout
// =============================================================================

// Import TypeScript type for metadata configuration
import type { Metadata } from "next";

// Import Google fonts using Next.js built-in font optimization
// This automatically hosts fonts locally for better performance
import { Geist, Geist_Mono } from "next/font/google";

// Import global CSS styles that apply to the entire application
import "./globals.css";

// =============================================================================
// FONT CONFIGURATION
// =============================================================================
// Next.js font optimization:
//   - Fonts are downloaded at build time and hosted with your other static assets
//   - No network requests to Google at runtime (better privacy & performance)
//   - Automatic font fallback to prevent layout shift
//   - CSS variables allow using fonts anywhere in your app

// Configure Geist Sans font (for regular text)
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name to reference this font
  subsets: ["latin"], // Only include Latin characters (reduces file size)
});

// Configure Geist Mono font (for code/monospace text)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable name to reference this font
  subsets: ["latin"], // Only include Latin characters
});

// =============================================================================
// METADATA CONFIGURATION
// =============================================================================
// Metadata is used for SEO and browser tab information.
// This is a Server Component feature - metadata is generated on the server.
//
// You can also export metadata from individual page.tsx files to override
// or extend the root metadata for specific pages.
//
// Common metadata options:
//   - title: Browser tab title
//   - description: Search engine description
//   - keywords: SEO keywords
//   - openGraph: Social media sharing preview
//   - icons: Favicon configuration

export const metadata: Metadata = {
  title: "Create Next App", // Shown in browser tab
  description: "Generated by create next app", // Used by search engines
};

// =============================================================================
// ROOT LAYOUT COMPONENT
// =============================================================================
// This component wraps every page in your application.
//
// Props:
//   - children: The page content (or nested layouts) to render
//
// The Readonly<> wrapper ensures TypeScript treats the props as immutable.
// React.ReactNode allows any valid React content as children.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // The <html> tag MUST be in the root layout (required by Next.js)
    <html lang="en">
      {/* The <body> tag MUST also be in the root layout */}
      {/* Apply font CSS variables and Tailwind's antialiased class for smoother fonts */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* children = the page content or nested layouts */}
        {/* This is where your pages will be rendered */}
        {children}
      </body>
    </html>
  );
}
